#!/usr/bin/env python
"""Riffle shuffle + square-up: a joint trajectory for the two YAM arms with
Sharpa hands, generated by IK from the layout of the C-IPC "precision card shuffle" scene.

The reference has no hands: every card is held by two Dirichlet rows -- its
lower-outer short edge and its upper-inner short edge -- which bow the two
tented packets, release the cards one by one from the bottom, and two plates
then square the pile. Here the hands take over those roles:

  four fingertips -> the packet's lower-outer END FACE, pinned at table level
                     (all four on the edge line; distal phalanges near
                     vertical, 7-35 deg off -- the long middle finger has to
                     curl to land on the others' line); during the riffle
                     they double as the outer stops
  thumb tip       -> the upper-inner end face: presses down to bow the packet,
                     then -- the THUMB ALONE, arm and fingers still -- slides
                     across the packet's thickness (up and outward), letting
                     the cards spring off from the bottom; the right hand
                     leads the left by one solver step, as in the reference
  fingertip rake  -> the plates, and the square-up: the same four fingertips,
                     side by side (6.1 cm across, inside the 7 cm card depth),
                     sweep the pile's ends toward the centre at the plates'
                     constant speed (4 cm/s x scale), from where the plates
                     start to the card
                     length + --square-slack (the plates stop 0.7 cm short of
                     one squared stack), hold, back off and leave.
                     (Flat parallel "plate" hands do not work on this rig:
                     the two arms are identical, not mirrored, so the left
                     forearm rides inboard of its wrist and the forearms
                     cross over the pile. The hands therefore lean in a few
                     degrees at the end of the push.)

Geometry is the reference's scaled by --scale (default 1.25: the Sharpa hand
is ~1.25x a human hand, so the cards become 11.1 x 7.0 cm), floor = the table
(z = 0), packets --zlift above it (0.6 cm; reference 0.07 cm scaled). It is
meant to be adapted on the cards' side; the file records what it aimed for.

    uv run python tool/ik/gen_shuffle_motion.py [options] --out output/ik/<name>   # -> shuffle_motion.npz, report.json
    uv run python tool/bake_hand_shuffle.py --motion output/ik/<name>/shuffle_motion.npz --out asset/<asset>

The robot model (URDFs and meshes) is asset/robot/yam_sharpa, loaded through tool/robot; the options that
produced the shipped motions are in the README.

Output npz (lengths cm, rig frame: Z up, table z = 0, robot at y ~ 0):
  joint_q [F, 56] rad   left arm 6 + hand 22, right arm 6 + hand 22 (bench order)
  fps, phase_names / phase_start / phase_end (inclusive frame ranges)
  body_q [F, 86, 7]     world link transforms (xyz cm + quaternion xyzw), body_names
  joint_names
  target_left / target_right [F, 7]   thumb-tip target xyz, middle-fingertip
                        target xyz, mode (0 grasp, 1 rake), in WORLD
                        coordinates of each hand; NaN where a phase does not
                        steer that contact (joint-space moves, parked thumb)
  table_exact_cm [F]    lowest robot mesh vertex above the table (exact)
  arm_gap_cm [F]        left-right gap by covering spheres (conservative)
  arm_gap_exact_cm [F]  mesh gap by vertices (stride 4, forearm outward; reads
                        up to 0.1 cm high), every 3rd frame (NaN elsewhere)
  thumb_finger_gap_cm [F]  thumb to the same hand's fingers (covering spheres)
  scene                 json: scale, card size, packet pose, contact points, floor
"""
from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np

sys.path[:0] = [os.path.dirname(os.path.abspath(__file__)), os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "robot")]
from robot_scene import YamSharpaBench  # noqa: E402
from yam_kin import (Above, ArmKin, Axis, Point, Posture, Proxies, exact_gap)  # noqa: E402

# ---- reference scene (cm, scale 1), contact_solver card-shuffle-reproduction
CARD_LEN, CARD_DEPTH = 8.89, 5.6
PACKET_CX, PACKET_CZ = 5.0, 3.2      # card 0's centre: |x|, height above floor
PACKET_THICK = 27 * 0.0311           # 27 cards, 0.311 mm pitch
BOW = 0.5                            # each grip row travels 5 mm
PLATE_X0, PLATE_X1 = 9.0, 5.0        # plates: |x| 9 cm -> 5 cm in 1 s (constant)
RELEASE_LAG = 0.02                   # right card i one solver step before left

# contact points in a distal-phalanx frame (x toward the tip, y out of the
# pad), measured on the link meshes: fingers end at x = 2.76 with the pad-side
# surface at y = 0.5 near x = 2.3; the thumb's distal chain ends at x = 3.24
FINGER_TIP = (2.3, 0.5, 0.0)
THUMB_TIP = (3.1, -0.2, 0.0)
# the thumb's pad: the apex of the fleshy bump on the pad side of the distal phalanx (measured on the
# link mesh: y peaks at 0.69 near x = 1.2), 17 mm wide across the phalanx. --thumb-grasp pad targets
# this point instead of the tip and lays the pad on the packet's end face (a person riffles with the
# pad, not the tip): the card edges then meet a flat surface as wide as the packet is thick.
THUMB_PAD = (1.2, 0.69, 0.0)
PAD_N = (0.0, 1.0, 0.0)
TIP_DIR = (1.0, 0.0, 0.0)
# the fingertip cap's lowest candidates (tip end, pad side, back), for the
# table hinge: a tilted fingertip reaches lower than its axis
CAP = ((2.76, 0.0, 0.0), (2.71, -0.58, 0.0), (2.71, 0.2, 0.0),
       (2.45, 0.45, 0.0), (2.45, -0.75, 0.0), (2.5, 0.0, 0.7), (2.5, 0.0, -0.7))
FINGERS = ("index", "middle", "ring", "pinky")
# a finger's last joint follows its middle joint, as in a real hand
DIP_TIES = [(f"{f}_DIP", f"{f}_PIP", 0.0, 0.6) for f in FINGERS]
FINGER_DY = {"index": 3.05, "middle": 1.0, "ring": -1.0, "pinky": -3.05}
# posture weights (per rad, against 1 per cm on the contacts): the fingers'
# curl preference, and the thumb's two abduction joints (CMC, MCP) toward
# mid-range -- see Hand.__init__
W_CURL = 0.1
W_CURL_RAKE, RAKE_CURL = 0.1, 0.45   # the rake's own curl weight / amount
W_THUMB_AA = (2.0, 2.0)
# the table hinge acts on the CAP points; the mesh reaches this much lower
CAP_MARGIN = 0.03
PLATE_SPEED = 4.0                    # cm/s at scale 1 (0.8 mm per 0.02 s step)
RIFFLE_RAMP, PUSH_RAMP = 0.10, 0.12  # cruise() ramps, fraction of the phase
HANDOVER = 15                        # frames to fade an IK hand-over residual
# The fingertip pad point's working height above the table, in the hold and in
# the rake: any lower and the table hinge on the rounded cap fights the contact
# target (ik error, then solution flips: 200-360 rad/s2 with the packets at
# 60-65 deg, whose mid-face contact is 0.9 cm high).
FINGER_Z = 1.04
# back-of-the-thumb points (distal / proximal phalanx frames) and the distance
# they keep from the centreline
THUMB_BACK = (("thumb_DP", (0.0, -0.9, 0.0)), ("thumb_DP", (1.6, -0.9, 0.0)),
              ("thumb_DP", (3.0, -0.5, 0.0)), ("thumb_PP", (0.0, -1.0, 0.0)))
THUMB_KEEP = 1.3


def minjerk(a):
    a = np.clip(a, 0.0, 1.0)
    return a * a * a * (10.0 - 15.0 * a + 6.0 * a * a)


def stair(a, n_cards, gap_frac, approach_frac, jump_frac):
    """Staircase progress for the riffle (--riffle-stair): a min-jerk approach to gap_frac over the first
    approach_frac of the segment, then n_cards equal jumps (each a min-jerk lasting jump_frac of a period,
    the pad standing still in between). Contact-solver feedback: swept at constant speed, a flat pad's edge
    crosses a card's end over ~0.3 mm of travel, so the card straightens gradually and falls slowly; a jump
    of one card pitch per period frees exactly one card, fully bowed, per period."""
    a = float(np.clip(a, 0.0, 1.0))
    if a < approach_frac:
        return gap_frac * float(minjerk(a / approach_frac))
    p = (1.0 - approach_frac) / n_cards
    k = min(int((a - approach_frac) // p), n_cards - 1)
    local = (a - approach_frac - k * p) / p
    pitch_frac = (1.0 - gap_frac) / n_cards
    return gap_frac + (k + float(minjerk(min(1.0, local / jump_frac)))) * pitch_frac


def cruise(a, ramp=0.12):
    """Constant speed with short smooth ends (the plates move at constant
    speed; a min-jerk push would hit the cards at twice the mean speed)."""
    a = float(np.clip(a, 0.0, 1.0))
    v = 1.0 / (1.0 - ramp)
    if a < ramp:
        return 0.5 * v * a * a / ramp
    if a > 1.0 - ramp:
        return 1.0 - 0.5 * v * (1.0 - a) ** 2 / ramp
    return v * (a - 0.5 * ramp)


def unit(v):
    v = np.asarray(v, dtype=float)
    return v / np.linalg.norm(v)


class Hand:
    """One arm + hand, working in LEFT-hand task coordinates: every target is
    written for the left side and mirrored (x -> -x) for the right."""

    # Taking the thumb off the cards: interpolating all five joints at once
    # swings the tip 0.6 cm TOWARD the other thumb before it clears.
    # De-opposing first (CMC), then straightening (MCP, IP) moves the tip
    # monotonically outward; parked fully de-opposed it sits 1.5 cm inside
    # the palm plane (half-opposed, the two thumbs meet over the pile).
    THUMB_REST = {"thumb_CMC_FE": (0.0, 0.7, 0.0), "thumb_CMC_AA": (0.0, 0.7, 0.0),
                  "thumb_MCP_FE": (0.45, 1.0, 0.1), "thumb_MCP_AA": (0.45, 1.0, 0.0),
                  "thumb_IP": (0.45, 1.0, 0.15)}

    def __init__(self, bench, side, args):
        self.kin = k = ArmKin(bench, side)
        self.px = Proxies(bench, k)
        self.args = args
        self.thumb_pt = THUMB_PAD if args.thumb_grasp == "pad" else THUMB_TIP
        th_ = np.radians(args.tilt)
        self.card_axis = np.array([-np.cos(th_), 0.0, -np.sin(th_)])       # down card 0, left packet
        self.M = np.array([1.0, 1.0, 1.0]) if side == "left" else \
            np.array([-1.0, 1.0, 1.0])
        self.ax = k.hand_axes()
        # flexion only: the abduction joints stay at 0. (Freed, the solver
        # uses ONE finger's abduction as a cheap yaw and drives it through
        # its neighbour.)
        flex = [k.jidx[f"{f}_{j}"] for f in FINGERS for j in ("MCP_FE", "PIP")]
        self.rake_vars = k.ARM + flex
        self.grasp_vars = self.rake_vars + k.THUMB
        # The riffle is the thumb alone, all five joints: its three flexion
        # joints are nearly singular along the slide (3 rad/s of IP per cm/s)
        # and need the two abduction joints (0.2 rad/s with them), which
        # travel ~0.12 rad over it. So the hold and the bow pin them near
        # mid-range (W_THUMB_AA, stiff): left to a weak preference the hold
        # saturates CMC_AA, and every arrival at / departure from a bound
        # kinks all the other joints (14 rad/s2 in the bow, 25 in the slide).
        self.thumb_aa = [k.jidx["thumb_CMC_AA"], k.jidx["thumb_MCP_AA"]]
        self.digit_links = {d: [k.b(f"{d}_{l}") for l in
                                (("PP", "DP", "elastomer") if d == "thumb"
                                 else ("PP", "MP", "DP", "elastomer"))]
                            for d in ("thumb",) + FINGERS}

    # -- hand shapes -----------------------------------------------------
    def preshape(self, curl):
        k, q = self.kin, np.zeros(self.kin.n_q)
        for n, v in (("thumb_CMC_FE", 1.0), ("thumb_MCP_FE", 0.4),
                     ("thumb_IP", 0.4)):
            q[k.jidx[n]] = v
        for f in FINGERS:
            q[k.jidx[f + "_MCP_FE"]] = curl
            q[k.jidx[f + "_PIP"]] = curl
            q[k.jidx[f + "_DIP"]] = 0.6 * curl
        return q

    def thumb_release(self, q, q_from, a):
        """Thumb joints at fraction `a` of the staged opening from q_from."""
        k, q = self.kin, q.copy()
        for name, (a0, a1, rest) in self.THUMB_REST.items():
            w = minjerk((a - a0) / (a1 - a0))
            q[k.jidx[name]] = (1.0 - w) * q_from[k.jidx[name]] + w * rest
        return q

    # -- IK problems -----------------------------------------------------
    def _pad_dirs(self):
        """The grasp's fingertip orientation: --pad-tilt degrees up from vertical pads facing inward.
        Contact-solver feedback: a vertical pad answers a card's axial thrust with a horizontal force
        whose inward part levers the card's top edge outward along the thumb; a pad facing the
        packet's lower end face pushes each card along its own axis."""
        t = np.radians(self.args.pad_tilt)
        return unit([np.cos(t), 0.0, np.sin(t)]), (np.sin(t), 0.0, -np.cos(t))

    def _fingers(self, G, pad_dir, curl, wrist_x, link4_x, w_vertical,
                 w_curl=None, tip_dir=(0.0, 0.0, -1.0), dz=0.0):
        """Four fingertips on the line through G along y (the card edge):
        the middle one pinned in y so the hand is centred on the packet, the
        others free to sit where the hand's finger spacing puts them."""
        k, M = self.kin, self.M
        # the curl preference is what keeps the finger joints off their
        # bounds (a joint arriving at a bound kinks every other joint)
        w_shape = np.full(k.n_q, W_CURL if w_curl is None else w_curl)
        w_shape[:6] = 0.0
        w_shape[self.thumb_aa] = W_THUMB_AA
        terms = []
        idx = getattr(self, "index_target", None)
        for f in FINGERS:
            full = f == "middle"
            if f == "index" and idx is not None and self.args.index_press > 0:
                # --index-press: the index finger presses the packet's outer face just below the thumb (a human
                # riffle grip), its pad facing into the packet. Contact-solver feedback: a thumb swept across the
                # stack drags the card tops along by friction unless the packet's body is held near the top.
                terms += [Point("index_DP", FINGER_TIP, idx * M, w=self.args.index_weight),
                          Axis("index_DP", PAD_N, self.index_dir * M, w=0.3)]
                terms += [Above("index_DP", c, (0, 0, 1), self.args.table_gap + CAP_MARGIN, w=5.0) for c in CAP]
                continue
            terms += [
                Point(f + "_DP", FINGER_TIP,
                      (G + np.array([0.0, FINGER_DY[f], 0.0])) * M, w=1.0,
                      mask=(1.0, 1.0 if full else 0.0, 1.0)),
                Axis(f + "_DP", TIP_DIR, np.array(tip_dir) * M, w=w_vertical),
                Axis(f + "_DP", PAD_N, pad_dir * M, w=w_vertical)]
            terms += [Above(f + "_DP", c, (0, 0, 1),
                            self.args.table_gap + CAP_MARGIN + dz, w=5.0)
                      for c in CAP]
        terms += [
            Axis("hand_wrist", self.ax["thumb_side"], (0.0, 1.0, 0.0), w=1.0),
            Above("hand_wrist", (0, 0, 0), (-M[0], 0, 0), wrist_x, w=1.0),
            Above("link4", (0, 0, 0), (-M[0], 0, 0), link4_x, w=1.0),
            Above("hand_wrist", (0, 0, 0), (0, 0, 1), 8.0, w=1.0),
            Above("link4", (0, 0, 0), (0, 0, 1), 12.0, w=0.5),
            Posture(self.preshape(curl), w=w_shape)]
        return terms

    def grasp_terms(self, T, G, q_prev=None):
        a, M = self.args, self.M
        pd, td = self._pad_dirs()
        terms = self._fingers(G, pd, 0.7, a.wrist_x, a.link4_x, 0.3, tip_dir=td)
        # the two thumbs face each other across the centreline: keep the back
        # of each one on its own side (idle unless the packets stand close)
        terms += [Above(b, c, (-M[0], 0, 0), THUMB_KEEP, w=2.0)
                  for b, c in THUMB_BACK]
        if a.thumb_grasp == "pad":
            terms += [Point("thumb_DP", THUMB_PAD, T * M, w=1.0),
                      Axis("thumb_DP", PAD_N, self.card_axis * M, w=a.pad_axis_weight)]   # the pad faces down the card, onto the end face
        else:
            op = np.radians(a.thumb_open)      # --thumb-open: the tip turned from straight down toward the card axis
            terms += [Point("thumb_DP", THUMB_TIP, T * M, w=1.0),
                      Axis("thumb_DP", TIP_DIR, np.array([-np.sin(op), 0.0, -np.cos(op)]) * M, w=0.5)]
        terms += [
            Point("hand_wrist", (0, 0, 0), (0, a.wrist_y, 0), w=0.15,
                  mask=(0, 1, 0), hard=False)]
        if q_prev is not None:
            w_prev = np.full(self.kin.n_q, 0.12)
            w_prev[self.kin.THUMB] = 0.4      # no wandering in the null space
            terms.append(Posture(q_prev, w=w_prev))
        return terms

    def rake_terms(self, P, thumb_x, q_prev=None):
        """The rake: fingertips at P, pads facing the centre. The thumb joints
        are not solved here (they are parked), but its tip is kept at least
        `thumb_x` from the centreline."""
        a, M = self.args, self.M
        # --push-z < 0: the rake's caps may go that much below the table gap (the push with the finger's straight
        # segment: the round tip is 16 mm across and the squared deck's face 15 mm tall, so at any height the tip's
        # slope either lifts the top cards or pins the bottom ones; the cylinder above it pushes flat).
        terms = self._fingers(P, unit([1.0, 0.0, 0.0]), RAKE_CURL, a.rake_wrist_x,
                              a.link4_x, 0.2, w_curl=W_CURL_RAKE, dz=min(0.0, a.push_z))
        terms.append(Above("thumb_DP", THUMB_TIP, (-M[0], 0, 0), thumb_x, w=1.0))
        if q_prev is not None:
            terms.append(Posture(q_prev, w=0.12))
        return terms

    def lift_terms(self, G, q_prev):
        """The grasp's finger problem without the thumb (--lift-clear): the four
        fingertips on the line through G, the hand as in the hold, anchored
        firmly on the previous frame (this phase takes over from 330 frames of
        thumb-only solves, and a weak anchor lets the arm re-balance in one)."""
        a, M = self.args, self.M
        pd, td = self._pad_dirs()
        terms = self._fingers(G, pd, 0.7, a.wrist_x, a.link4_x, 0.3, tip_dir=td)
        terms += [Above(b, c, (-M[0], 0, 0), THUMB_KEEP, w=2.0)
                  for b, c in THUMB_BACK]
        terms += [Point("hand_wrist", (0, 0, 0), (0, a.wrist_y, 0), w=0.15,
                        mask=(0, 1, 0), hard=False),
                  Posture(q_prev, w=5.0)]
        return terms

    def regrip_terms(self, P, thumb_x, w, q_prev):
        """From the grasp to the rake WITHOUT leaving the cards (--direct-push): the
        four fingertips stay on the line through P while the hand's preferences
        blend from the grasp's (w = 0) to the rake's (w = 1); the thumb joints are
        staged by thumb_release outside the solve."""
        a, M = self.args, self.M
        mix = lambda g, r: (1.0 - w) * g + w * r
        terms = self._fingers(P, unit([1.0, 0.0, 0.0]), mix(0.7, RAKE_CURL),
                              mix(a.wrist_x, a.rake_wrist_x), a.link4_x, mix(0.3, 0.2),
                              w_curl=mix(W_CURL, W_CURL_RAKE))
        terms.append(Above("thumb_DP", THUMB_TIP, (-M[0], 0, 0), thumb_x, w=w))
        # firm anchor at the hand-over from the thumb-only riffle, the rake's own (0.12) at the
        # end, so that the last regrip frame IS the rake problem and the push starts without a hop
        terms.append(Posture(q_prev, w=mix(2.0, 0.12)))
        return terms

    def thumb_terms(self, T, q_prev, roll=0.0, axis0=None, hold_axis=False, axis_w=0.5):
        """The riffle's per-frame problem (thumb alone). --riffle-roll: the tip's axis (`axis0`: its direction
        at the riffle's start, in the solver's frame) turns about y by `roll` (rad, growing over the riffle)
        with the tip's end moving toward the centre, so the tip's underside rises on its trailing (inner)
        side and dips on the leading side. Contact-solver feedback: a tip that only translates across the
        packet's end faces unloads the cards behind it together and they leave in bunches; with the underside
        ramped, each card behind the tip loses its compression in turn."""
        terms = [Point("thumb_DP", self.thumb_pt, T * self.M, w=1.0), Posture(q_prev, w=0.1)]
        if axis0 is not None and (roll or hold_axis):      # --riffle-hold-axis: roll 0 keeps the grasp's tip direction
            c, sn = np.cos(roll), np.sin(roll)
            a = np.array([c * axis0[0] - sn * axis0[2], axis0[1], sn * axis0[0] + c * axis0[2]])   # R_y(-roll) axis0
            terms.append(Axis("thumb_DP", TIP_DIR, a, w=axis_w))
        return terms

    def settle(self, q, vars, terms_fn, iters=40):
        """Fixed point of the continuity-anchored problem: the pose that is
        its own optimum when the anchor sits on it. A key pose solved with
        the anchor elsewhere makes the first tracked frame hop."""
        k = self.kin
        for _ in range(iters):
            q_new = k.solve(q, vars, terms_fn(q), ties=DIP_TIES).q
            if np.abs(q_new - q).max() < 1e-6:
                return q_new
            q = q_new
        return q

    def thumb_finger_gap(self, fk):
        """Thumb vs the four fingers, covering spheres (conservative)."""
        c = self.px.world(fk)
        th = np.isin(self.px.body, self.digit_links["thumb"])
        fi = np.isin(self.px.body, sum((self.digit_links[f] for f in FINGERS), []))
        d = np.linalg.norm(c[th][:, None] - c[fi][None], axis=2)
        return float((d - self.px.radius[th][:, None]
                      - self.px.radius[fi][None]).min())


def contact_err(h, fk, tgt):
    """Worst distance (cm) of the steered contact points from the recorded
    targets: thumb tip and middle fingertip in 3-D, the other fingertips from
    the middle one's line (x, z). Measured by FK, not the solver's word."""
    if np.isnan(tgt[3]):
        return 0.0
    k, e = h.kin, 0.0
    if not np.isnan(tgt[0]):
        e = np.linalg.norm(fk.point(k.b("thumb_DP"), h.thumb_pt) - tgt[0:3])
    for f in FINGERS:
        d = fk.point(k.b(f + "_DP"), FINGER_TIP) - tgt[3:6]
        if f != "middle":
            d[1] = 0.0
        e = max(e, np.linalg.norm(d))
    return float(e)


def build(args):
    S, yc, fps = args.scale, args.yc, args.fps
    bench = YamSharpaBench(device="cpu", with_table=False)
    hands = {s: Hand(bench, s, args) for s in ("left", "right")}

    # ---- task geometry, LEFT packet (the right one is its x-mirror) -------
    half = 0.5 * CARD_LEN * S
    thick = (args.packet_thick if args.packet_thick > 0 else PACKET_THICK) * S   # --packet-thick: the 27 cards' stack (cm at scale 1)
    bow = args.bow * S
    up, inward = np.array([0, 0, 1.0]), np.array([1.0, 0, 0])
    # packet pose: --tilt from the table (reference 45 deg) and --top-x, |x| of card 0's
    # upper-inner edge (reference 2.32 cm). Card 0's lower-outer edge keeps the reference
    # height whatever the tilt. A steeper, closer packet lands its cards further across the
    # centreline: the two piles then share most of their length before the push (contact-solver
    # feedback: at 45 deg / 2.32 cm they share 1.9 cm of 11.1 and the push buckles them).
    th = np.radians(args.tilt)
    u = np.array([-np.cos(th), 0.0, -np.sin(th)])    # down card 0: upper-inner -> lower-outer
    n_p = np.array([-np.sin(th), 0.0, np.cos(th)])   # card stacking direction (card 0 lowest)
    c45 = np.cos(np.radians(45.0))
    top_x = args.top_x if args.top_x > 0 else PACKET_CX * S - half * c45
    G0 = np.array([-(top_x + 2.0 * half * np.cos(th)), yc,
                   PACKET_CZ * S - half * c45 + args.zlift])
    T0 = G0 - 2.0 * half * u                            # card 0's two short edges
    centre = 0.5 * (T0 + G0)
    # --bow-thumb / --bow-fingers: how much of the bow each side does (1 / 1 = the reference: thumb down and fingers
    # in by `bow`). Contact-solver feedback: with the fingers moving in, the near-vertical pads shove the outer cards'
    # lower edges while the thumb holds their tops, and a packet held by contact alone levers its outer cards up the
    # thumb; with the thumb doing the whole bow, every card it covers is compressed along its own axis.
    # --bow-dir card: the bow moves the thumb down the card axis and the fingers up it, instead of the
    # thumb straight down and the fingers straight in. Contact-solver feedback: on a 45-degree packet
    # half of a vertical thumb descent is a shift across the end face toward the inner cards; scripted
    # rows follow the thumb, free cards held at the bottom by the fingers do not, and the outer cards end
    # up on the tip's flank and are squeezed out along it. Along the axis the tip stays over the same cards.
    bow_t = (u if args.bow_dir == "card" else -up) * bow * args.bow_thumb
    fdir = args.bow_dir if args.bow_fingers_dir == "auto" else args.bow_fingers_dir
    bow_g = (-u if fdir == "card" else inward) * bow * args.bow_fingers
    T0_bow, G0_bow = T0 + bow_t, G0 + bow_g
    # contacts: the middle of the upper END FACE (the 27 edges span
    # thick * n_p); on the lower one the point at the fingertips' working
    # height (the middle at 45 deg, higher up the face on a steeper packet)
    t_g = float(np.clip((FINGER_Z - G0[2]) / n_p[2], 0.15 * thick, 0.85 * thick))
    Tc, Gc = T0 + 0.5 * thick * n_p, G0 + t_g * n_p
    # --thumb-inset: the grasp target moved down the end face toward card 0 (cm). Contact-solver
    # feedback: with the thumb pointing down onto the 45-degree face, the part of the distal link
    # that faces the card edges sits ~3 mm toward the top cards of where the tip point is, so the
    # bottom cards have no thumb in front of them and a packet held by contact alone tips that way.
    # The riffle still ends past the top card's edge: the sweep is longer by the inset.
    Tc = Tc - args.thumb_inset * n_p
    if args.index_press > 0:      # the index finger's press point: on the packet's outer face, --index-press down the card from the top edge
        u_card = unit(G0 - T0)
        for hh in hands.values():
            hh.index_press_pt = T0 + (thick + args.index_gap) * n_p + args.index_press * u_card
            hh.index_target = hh.index_press_pt if args.index_from == "approach" else None
            hh.index_dir = -n_p
        print("index press: %.1f cm below the top edge on the packet's outer face, tip %.2f cm outside it" % (args.index_press, args.index_gap))
    Tc_bow, Gc_bow = Tc + bow_t, Gc + bow_g
    # --riffle-lift: over the riffle the thumb also withdraws this far (cm) up the card axis, so the pinch on a
    # card vanishes when the tip passes it. Contact-solver feedback: swept across at a fixed depth, the rounded
    # outer flank carries the outer half of a packet along instead of letting it go.
    if args.riffle_mode == "lift":  # no sweep across the stack at all: the thumb only retreats up the card axis
        args.riffle_extra = -(thick + args.thumb_inset)
        print("riffle lift mode: the thumb retreats %.2f cm up the card axis over the riffle (%.2f cm before the first card lets go, "
              "then evenly), no motion across the stack" % (args.riffle_lift, args.riffle_stair_gap))
    if args.riffle_stair > 0 and args.riffle_mode != "lift":      # the sweep is then exactly the approach gap plus 27 card pitches
        args.riffle_extra = args.riffle_stair_gap + 27 * args.riffle_stair - thick - args.thumb_inset
        print("riffle staircase: pitch %.3f cm, gap %.3f cm, sweep %.3f cm (extra %.3f)" % (
            args.riffle_stair, args.riffle_stair_gap, thick + args.thumb_inset + args.riffle_extra, args.riffle_extra))
    Tc_end = Tc_bow + (thick + args.thumb_inset + args.riffle_extra) * n_p - args.riffle_lift * u   # past the top card's edge
    Tc_off = Tc_end + 0.6 * up
    lift = args.hover * up
    Tc_pre, Gc_pre = Tc + lift + 1.5 * up, Gc + lift - 1.5 * inward
    z_rake = Gc[2]
    # the rake starts where the reference plates start, but ends on the
    # card length (the plates stop 0.55 cm short of a squared stack)
    # --rake-start: |x| where the rake comes down (cm); default = where the reference plates start.
    # Contact-solver feedback: cards that slid outward while the hands were away lie at 11.5-12.4 cm,
    # and a fingertip landing on one pinches it against the table (no feasible step).
    x_out = -(args.rake_start if args.rake_start > 0 else PLATE_X0 * S)
    x_in = (-PLATE_X1 * S if args.square_slack < 0
            else -(half + args.square_slack))
    # --direct-push: no lift-off between the riffle and the push. The fingertips stay where the
    # riffle left them (at the pile's outer ends, as backstops) while the thumb is parked, move out by
    # --regrip-retreat, and push from there. Contact-solver feedback: with the hands away for 2 s the
    # top cards slide off the pile (its top slopes 0.04-0.09, card on card has friction 0.02-0.05).
    if args.direct_push:
        x_out = Gc_bow[0] - args.regrip_retreat
    P_high = np.array([x_out, yc, z_rake + args.hover])
    P_out = np.array([x_out, yc, z_rake])
    # --push-z: the fingertips rise by this much (cm) over the push, so its end is that much higher than the rake height.
    # Contact-solver feedback: at the rake height the caps' lowest point is 3 mm below the mat's top, so the bottom
    # cards' outer edges are pushed by the caps' downward-facing slope and pressed into the mat; the push locks the
    # solver once the deck is squared to about 141 mm. A cap pushing at its equator has no such wedge.
    P_in = np.array([x_in, yc, z_rake + args.push_z])
    P_back = np.array([x_in - 1.5, yc, z_rake + args.push_z])
    P_up = np.array([x_in - 3.0, yc, z_rake + args.push_z + args.hover])
    thumb_x = abs(Tc_end[0])
    # --riffle-step: seconds per card per hand (reference 0.04 = one card per solver step, hands
    # alternating); --release-lag: how far the left hand trails the right. Contact-solver
    # feedback: a released card takes 0.2-0.28 s to come down, so at 0.04 s six cards per hand are
    # in flight at once and they land in runs of 4-7, which the push then jack-knifes; at a step
    # near the fall time, with the lag at half of it, they land one by one, alternating.
    lag = int(round((args.release_lag if args.release_lag >= 0 else RELEASE_LAG) * fps))
    # the push runs at the plates' speed over its own (longer) stroke
    v_push = PLATE_SPEED * S
    t_push = (x_in - x_out) / (v_push * (1.0 - PUSH_RAMP))
    n_push = max(1, int(round(t_push * fps)))
    v_push = (x_in - x_out) / ((n_push / fps) * (1.0 - PUSH_RAMP))

    def lerp(a, b):
        return lambda s: (1.0 - s) * a + s * b

    # (name, seconds, kind, payload); kinds: joint / task / thumb / hold
    seg = [
        ("reach", 2.0, "joint", "pre"),
        ("approach", 0.9, "joint", "hold"),
        ("hold", 0.4, "hold", dict(T=Tc, G=Gc)),
        ("bow", 1.0, "task", dict(T=lerp(Tc, Tc_bow), G=lerp(Gc, Gc_bow), index_arrive=(args.index_press > 0 and args.index_from == "bow"))),
        ("riffle", 27 * args.riffle_step, "hand_riffle" if args.riffle_hand else "thumb", dict(T=lerp(Tc_bow, Tc_end), lag=True)),
        ("riffle_done", 0.3, "thumb", dict(T=lerp(Tc_end, Tc_off))),
    ] + ([
        # --lift-clear: the whole grasp rises straight up first (task space, fingertips keep their x).
        # Contact-solver feedback: the last cards' lower edges sit wedged under the rounded fingertips;
        # the joint-space lift-off moves the tips outward from its first frame and drags them along.
        # The thumb is already off the cards: its joints stay as they are, arm and fingers carry it.
        ("lift_clear", args.lift_clear_time, "task",
         dict(G=lerp(Gc_bow, Gc_bow + args.lift_clear * up), fingers_only=True)),
    ] if args.lift_clear > 0 else []) + [
    ] + ([
        ("regrip", args.regrip_time, "regrip", dict(P=lerp(Gc_bow, P_out))),
    ] + ([("pause", args.push_pause, "hold", None)] if args.push_pause > 0 else []) if args.direct_push else [
        ("release_lift", 1.4, "joint", "rake_high"),
        ("lower", 0.6, "task", dict(P=lerp(P_high, P_out))),
    ]) + [
        ("push", n_push / fps, "task",
         dict(P=lerp(P_out, P_in), profile=lambda a: cruise(a, PUSH_RAMP))),
        ("squeeze", 0.4, "hold", None),
        ("back_off", 0.3, "task", dict(P=lerp(P_in, P_back))),
        # joint space: tracked, the table hinge lets go in one frame (17 rad/s2)
        ("withdraw", 0.8, "joint", "rake_up"),
        ("home", 2.2, "joint", "home"),
    ]
    n_of = [max(1, int(round(sec * fps)))
            + (lag if isinstance(p, dict) and p.get("lag") else 0)
            for _, sec, _, p in seg]
    # --riffle-cut F: only the first F frames of the riffle are emitted (its schedule, hence every frame before F, is
    # unchanged); the withdrawal, the park, the pause and the push follow from there. Contact-solver feedback: with the
    # knuckle opening fast the cards are all down by riffle frame 70, and the rest of the 8.6 s slide is dead time.
    n_emit = [(min(n, int(round(args.riffle_cut))) if (name == "riffle" and args.riffle_cut > 0) else n) for (name, _, _, _), n in zip(seg, n_of)]
    starts = np.concatenate([[0], np.cumsum(n_emit)]).astype(int)
    phases = [(seg[i][0], int(starts[i]), int(starts[i + 1] - 1))
              for i in range(len(seg))]

    Q, targets = {}, {}
    for side, h in hands.items():
        k, M = h.kin, h.M
        # ---- key poses: hold decides the arm branch (multi-start), and every
        # key pose is settled so tracking can start from it without a hop
        sols = k.solve_multi(h.preshape(0.7), h.grasp_vars,
                             h.grasp_terms(Tc, Gc), ties=DIP_TIES,
                             n_starts=args.starts, seed=3)
        # a candidate must also clear the table with its whole mesh: the
        # hinges only watch the fingertips, the wrist and the forearm, and a
        # branch with the hand lying on its side passes them
        sols = [s for s in sols if s.pos_err < 0.4 and s.hinge < 0.1
                and h.px.exact_table(k.fk(s.q)) > args.table_gap - 0.1]
        if not sols:
            raise SystemExit(f"{side}: no feasible hold pose")
        best = min(sols, key=lambda s: s.cost)
        q_hold = h.settle(best.q, h.grasp_vars,
                          lambda q: h.grasp_terms(Tc, Gc, q_prev=q))
        q_pre = h.settle(q_hold, h.grasp_vars,
                         lambda q: h.grasp_terms(Tc_pre, Gc_pre, q_prev=q))
        keys = dict(home=k.home(), pre=q_pre, hold=q_hold)

        q = keys["home"].copy()
        Qs, Ts = [], []
        nan3 = np.full(3, np.nan)
        dy = np.array([0.0, FINGER_DY["middle"], 0.0])
        for (name, sec, kind, payload), n, n_e in zip(seg, n_of, n_emit):
            if kind == "hold":
                tgt = Ts[-1].copy() if payload is None else np.concatenate(
                    [payload["T"] * M, (payload["G"] + dy) * M, [0.0]])
                for _ in range(n):
                    Qs.append(q.copy()); Ts.append(tgt.copy())
                continue
            if kind == "joint":
                if payload == "rake_high":
                    parked = h.thumb_release(q, q, 1.0)
                    keys["rake_high"] = h.settle(
                        parked, h.rake_vars,
                        lambda qq: h.rake_terms(P_high, thumb_x, q_prev=qq))
                elif payload == "rake_up":
                    keys["rake_up"] = h.settle(
                        q, h.rake_vars,
                        lambda qq: h.rake_terms(P_up, thumb_x, q_prev=qq))
                q_from, q_to = q.copy(), keys[payload]
                for i in range(n):
                    a = (i + 1) / n
                    w = minjerk(a)
                    q = (1 - w) * q_from + w * q_to
                    if payload == "rake_high":    # staged, not linear, thumb
                        q = h.thumb_release(q, q_from, a)
                    Qs.append(q.copy()); Ts.append(np.full(7, np.nan))
                continue
            if kind == "regrip":
                tip = k.fk(q).point(k.b("middle_DP"), FINGER_TIP) * M
                e0 = tip - (payload["P"](0.0) + dy)
                q_from = q.copy()
                for i in range(n):
                    a_ = (i + 1) / n
                    w_ = float(minjerk(a_))
                    P = payload["P"](w_)
                    fade = 1.0 - float(minjerk((i + 1) / HANDOVER))
                    q = h.thumb_release(q, q_from, a_)
                    sol = k.solve(q, h.rake_vars,
                                  h.regrip_terms(P + fade * e0, thumb_x, w_, q),
                                  ties=DIP_TIES)
                    q = sol.q
                    Qs.append(q.copy())
                    Ts.append(np.concatenate([nan3, (P + dy) * M, [1.0]]))
                continue
            if kind == "hand_riffle":
                # --riffle-hand: the riffle moves the whole hand across the stack (arm + finger flexion; the thumb's
                # joints stay frozen) with the fingertips held where the bow left them, so the thumb keeps its
                # orientation exactly. Contact-solver feedback: swept by its own joints the thumb turns 17 deg over
                # the riffle (a tip-direction term cannot stop the roll about the phalanx, and pinning the direction
                # costs 8 mm of tip position), and a flat pad whose inner edge dips pushes the held card ends off it
                # in blocks instead of one per period.
                fk0 = k.fk(q); wb = k.b("hand_wrist")
                w0 = fk0.point(wb, (0.0, 0.0, 0.0))
                ax0 = fk0.direction(wb, (1.0, 0.0, 0.0)); az0 = fk0.direction(wb, (0.0, 0.0, 1.0))
                T0 = payload["T"](0.0)
                for i in range(n_e):
                    shift = lag if (payload.get("lag") and side == "left") else 0
                    n_move = n - (lag if payload.get("lag") else 0)
                    s = float(np.clip((i + 1 - shift) / n_move, 0.0, 1.0))
                    if args.riffle_stair > 0:
                        D = thick + args.thumb_inset + args.riffle_extra
                        approach_frac = 1.0 / 28.0
                        period_frames = (1.0 - approach_frac) * n_move / 27.0
                        s = stair(s, 27, args.riffle_stair_gap / D, approach_frac, args.riffle_stair_jump / period_frames)
                    else:
                        s = cruise(s, RIFFLE_RAMP)
                    T = payload["T"](s); dT = (T - T0) * M                     # the hand's shift so far (world frame)
                    terms = [t for t in h.lift_terms(Gc_bow, q) if not isinstance(t, Posture)] + [
                        Posture(q, w=args.riffle_hand_posture),
                        Point("hand_wrist", (0.0, 0.0, 0.0), w0 + dT, w=args.riffle_hand_weight),
                        Axis("hand_wrist", (1.0, 0.0, 0.0), ax0, w=args.riffle_hand_weight),
                        Axis("hand_wrist", (0.0, 0.0, 1.0), az0, w=args.riffle_hand_weight)]
                    sol = k.solve(q, h.rake_vars, terms, ties=DIP_TIES)
                    q = sol.q
                    Qs.append(q.copy()); Ts.append(np.concatenate([T * M, (Gc_bow + dy) * M, [0.0]]))
                continue
            if kind == "thumb":
                # the previous problem (whole grasp) left the tip a little off
                # its target, this one (thumb alone) would close that in one
                # frame: carry the residual over and fade it out
                tip = k.fk(q).point(k.b("thumb_DP"), h.thumb_pt) * M
                e0 = tip - payload["T"](0.0)
                axis0 = k.fk(q).direction(k.b("thumb_DP"), TIP_DIR)       # for --riffle-roll (solver frame)
                q_knuckle = None                                          # for --riffle-knuckle
            if kind == "task" and payload.get("fingers_only"):
                h.index_target = None                                   # the index rejoins the rake for the lift and after
                # same hand-over, for the middle fingertip
                tip = k.fk(q).point(k.b("middle_DP"), FINGER_TIP) * M
                e0 = tip - (payload["G"](0.0) + dy)
            for i in range(n_e):
                knuckle = (kind == "thumb" and payload.get("lag") and i + 1 > args.riffle_knuckle_from
                           and (args.riffle_knuckle != 0.0 or args.riffle_knuckle_press[0] != 0.0 or args.riffle_knuckle_mode == "slide"))
                if knuckle:
                    # --riffle-knuckle DEG [--riffle-knuckle-from F --riffle-knuckle-frames N --riffle-knuckle-mode M]: from frame F
                    # of the riffle (counted from its first frame, both hands) the thumb's last knuckle (thumb_IP) is prescribed:
                    # it opens by DEG, linearly over N frames (0: the rest of the riffle), from its value at frame F (DEG 0: it is
                    # locked there). Mode "freeze": the thumb stops sliding, the arm, fingers and the thumb's other joints keep
                    # the pose of frame F. Mode "slide": the tip keeps following the riffle's path (the other four thumb joints
                    # solve it), --riffle-knuckle-press CM FRAMES adding a descent of CM down the card axis over FRAMES from F.
                    # The motion up to frame F is the recorded one. Contact-solver feedback: in the recorded slide the IP
                    # flexes 23 deg (the tip turns) and the flank walks 4 mm up the outer cards, which straighten and lean on the
                    # nail; opening the knuckle of the frozen thumb frees them, but all at once (a straight, leaning stack
                    # topples when its support retreats 3 mm), so the slide must go on and the cards be bowed when it passes.
                    if q_knuckle is None:
                        q_knuckle = q.copy()
                    n_open = args.riffle_knuckle_frames if args.riffle_knuckle_frames > 0 else n - args.riffle_knuckle_from
                    s_open = min(1.0, (i + 1 - args.riffle_knuckle_from) / max(1.0, n_open))
                    ip = k.jidx["thumb_IP"]
                    q_ip = float(np.clip(q_knuckle[ip] - np.radians(args.riffle_knuckle) * s_open, k.lo[ip] + 0.02, k.hi[ip] - 0.02))
                    if args.riffle_knuckle_mode == "freeze":
                        q_f = q_knuckle.copy(); q_f[ip] = q_ip
                        pc, pf = args.riffle_knuckle_press
                        if pc != 0.0:
                            # --riffle-knuckle-press CM FRAMES in mode freeze: the thumb also descends CM down the card axis over
                            # FRAMES from frame F, the other four joints following the frozen thumb's tip (swung by the opening)
                            # plus that descent. Contact-solver feedback: opening the frozen thumb frees the leaning, straight
                            # cards all at once; pressing while it opens is meant to keep them bowed so each leaves on its own.
                            tip_f = k.fk(q_f).point(k.b("thumb_DP"), h.thumb_pt) * M                      # task frame
                            p0 = args.riffle_knuckle_press_from if args.riffle_knuckle_press_from > 0 else args.riffle_knuckle_from
                            T = tip_f + pc * float(minjerk(min(1.0, max(0.0, i + 1 - p0) / max(1.0, pf)))) * u
                            q_s = q.copy(); q_s[ip] = q_ip
                            q_f = k.solve(q_s, [j for j in k.THUMB if j != ip], h.thumb_terms(T, q_s)).q
                        q = q_f
                        Qs.append(q.copy())
                        Ts.append(np.concatenate([k.fk(q).point(k.b("thumb_DP"), h.thumb_pt), (Gc_bow + dy) * M, [0.0]]))   # the record: where the tip is
                        continue
                if kind == "thumb":
                    shift = lag if (payload.get("lag") and side == "left") else 0
                    n_move = n - (lag if payload.get("lag") else 0)
                    s = float(np.clip((i + 1 - shift) / n_move, 0.0, 1.0))
                    if payload.get("lag") and args.riffle_mode == "lift":
                        # --riffle-mode lift: a quick retreat to the first release, then a steady retreat that frees one
                        # card per period (the pad is tilted so the compression grows across the stack, --pad-tilt < 0).
                        # Contact-solver feedback: any pad motion across the stack carries the held card ends along by
                        # friction (the stack shears card over card), so an edge never passes them one by one.
                        D = args.riffle_lift; approach_frac = 1.0 / 28.0
                        period_frames = (1.0 - approach_frac) * n_move / 27.0
                        s = stair(s, 27, args.riffle_stair_gap / D, approach_frac, min(1.0, args.riffle_stair_jump / period_frames))
                    elif payload.get("lag") and args.riffle_stair > 0:
                        D = thick + args.thumb_inset + args.riffle_extra
                        approach_frac = 1.0 / 28.0
                        period_frames = (1.0 - approach_frac) * n_move / 27.0
                        s = stair(s, 27, args.riffle_stair_gap / D, approach_frac, args.riffle_stair_jump / period_frames)
                    else:
                        s = (cruise(s, RIFFLE_RAMP) if payload.get("lag")
                             else float(minjerk(s)))
                    T = payload["T"](s)
                    if payload.get("lag") and args.riffle_hold_depth_from > 0 and i + 1 > args.riffle_hold_depth_from:
                        # --riffle-hold-depth-from F: from frame F of the riffle the --riffle-lift withdrawal / descent stops and
                        # the tip keeps its depth along the card axis (the slide across the stack goes on). Contact-solver
                        # feedback: with a 5 mm descent the cards under the cap are metered at 3-6 mm of bow until step
                        # 1780, then the still deepening cap holds their ends at its bottom, where the friction cone keeps
                        # them (they are carried along instead of slipping off the inner shoulder).
                        s_hold = cruise(float(np.clip((args.riffle_hold_depth_from - shift) / n_move, 0.0, 1.0)), RIFFLE_RAMP)
                        T = T + args.riffle_lift * (s - s_hold) * u
                    if payload.get("lag") and args.riffle_lift_early[0] != 0.0:
                        # --riffle-lift-early D E: the thumb also moves D cm down the card axis (D < 0: up) over the
                        # first E frames of the riffle. Contact-solver feedback: as the tip starts to slide it turns
                        # about 6 degrees within 45 frames and its contact walks 4 mm up the cards, which straightens
                        # the packet; a matching early descent keeps the remaining cards bowed for the flank to flick.
                        de, ne = args.riffle_lift_early
                        T = T + de * float(minjerk(min(1.0, (i + 1) / max(1.0, ne)))) * u
                    fade = 1.0 - float(minjerk((i + 1) / HANDOVER))
                    if payload.get("lag") and args.riffle_roll != 0.0:
                        # --riffle-roll DEG [--riffle-roll-from F]: the tip's direction turns by DEG over the riffle, linearly in
                        # frames from frame F of the riffle (the grasp, bow and the first F frames stay the recorded motion).
                        # Negative: the tip's end turns outward, the thumb opening as it sweeps.
                        s_roll = float(np.clip((i + 1 - shift - args.riffle_roll_from) / max(1.0, n_move - args.riffle_roll_from), 0.0, 1.0))
                        roll = np.radians(args.riffle_roll) * s_roll
                    else:
                        roll = 0.0
                    if knuckle:                                        # mode slide: the IP prescribed, the rest solves the tip
                        pc, pf = args.riffle_knuckle_press
                        p0 = args.riffle_knuckle_press_from if args.riffle_knuckle_press_from > 0 else args.riffle_knuckle_from
                        T = T + pc * float(minjerk(min(1.0, max(0.0, i + 1 - p0) / max(1.0, pf)))) * u
                        q = q.copy(); q[ip] = q_ip
                        sol = k.solve(q, [j for j in k.THUMB if j != ip], h.thumb_terms(T + fade * e0, q))
                    else:
                        sol = k.solve(q, k.THUMB, h.thumb_terms(T + fade * e0, q, roll=roll, axis0=axis0,
                                                                hold_axis=bool(args.riffle_hold_axis) and bool(payload.get("lag")),
                                                                axis_w=float(args.riffle_axis_weight)))
                    tgt = np.concatenate([T * M, (Gc_bow + dy) * M, [0.0]])
                else:
                    s = payload.get("profile", minjerk)((i + 1) / n)
                    if payload.get("fingers_only"):
                        G = payload["G"](s)
                        fade = 1.0 - float(minjerk((i + 1) / HANDOVER))
                        sol = k.solve(q, h.rake_vars,
                                      h.lift_terms(G + fade * e0, q),
                                      ties=DIP_TIES)
                        tgt = np.concatenate([nan3, (G + dy) * M, [0.0]])
                    elif "P" in payload:
                        P = payload["P"](s)
                        sol = k.solve(q, h.rake_vars,
                                      h.rake_terms(P, thumb_x, q_prev=q),
                                      ties=DIP_TIES)
                        tgt = np.concatenate([nan3, (P + dy) * M, [1.0]])
                    else:
                        T, G = payload["T"](s), payload["G"](s)
                        if payload.get("index_arrive"):
                            # --index-from bow: the index leaves the rake and settles on the arch over the bow's second
                            # half (a human bows the packet first, then lets the index press the arch). Contact-solver
                            # feedback: pressed from the approach, the finger stops the arch forming and the inner cards
                            # slide off the thumb's inner flank before the riffle.
                            if i == 0:
                                idx0 = k.fk(q).point(k.b("index_DP"), FINGER_TIP) * M
                            w_i = float(minjerk(min(1.0, max(0.0, (s - 0.5) / 0.5))))
                            h.index_target = (1.0 - w_i) * idx0 + w_i * h.index_press_pt
                        sol = k.solve(q, h.grasp_vars,
                                      h.grasp_terms(T, G, q_prev=q),
                                      ties=DIP_TIES)
                        tgt = np.concatenate([T * M, (G + dy) * M, [0.0]])
                q = sol.q
                Qs.append(q.copy()); Ts.append(tgt)
        Q[side], targets[side] = np.array(Qs), np.array(Ts)

    Ql, Qr = Q["left"], Q["right"]
    joint_q = np.concatenate([Ql, Qr], axis=1)
    F = len(joint_q)

    # ---- diagnostics --------------------------------------------------------
    kl, kr = hands["left"].kin, hands["right"].kin
    pl, pr = hands["left"].px, hands["right"].px
    table = np.zeros(F); gap = np.zeros(F); who = [""] * F
    gap_x = np.full(F, np.nan); tf_gap = np.zeros(F); e = np.zeros(F)
    table[:] = np.nan; gap[:] = np.nan; tf_gap[:] = np.nan
    for f in range(0, F, args.check_every):
        fl, fr = kl.fk(Ql[f]), kr.fk(Qr[f])
        e[f] = max(contact_err(hands["left"], fl, targets["left"][f]),
                   contact_err(hands["right"], fr, targets["right"][f]))
        table[f] = min(pl.exact_table(fl), pr.exact_table(fr))
        ca, cb = pl.world(fl), pr.world(fr)
        D = (np.linalg.norm(ca[:, None] - cb[None], axis=2)
             - pl.radius[:, None] - pr.radius[None])
        i, j = divmod(int(np.argmin(D)), D.shape[1])
        gap[f] = D[i, j]
        who[f] = f"{kl.names[pl.body[i]]}|{kr.names[pr.body[j]]}"
        tf_gap[f] = min(hands["left"].thumb_finger_gap(fl),
                        hands["right"].thumb_finger_gap(fr))
        if f % (3 * args.check_every) == 0:
            gap_x[f] = exact_gap(pl, fl, pr, fr)
    vel = np.abs(np.diff(joint_q, axis=0)) * fps
    acc = np.abs(np.diff(joint_q, n=2, axis=0)) * fps * fps
    lo = np.concatenate([kl.lo, kr.lo]); hi = np.concatenate([kl.hi, kr.hi])
    lim = np.minimum(joint_q - lo, hi - joint_q)
    arm_cols = np.r_[0:6, kl.n_q:kl.n_q + 6]
    moving = np.ptp(joint_q, axis=0) > 0.02        # joints the motion uses
    hand_cols = np.setdiff1d(np.flatnonzero(moving), arm_cols)
    # a joint arriving at / leaving the solver's bound while the pose is being
    # tracked is what kinks a trajectory: list every such event
    names = ([f"left_{n}" for n in kl.joint_names]
             + [f"right_{n}" for n in kr.joint_names])
    on = lim < 0.02 + 1e-5
    tracked = {"bow", "riffle", "riffle_done", "lift_clear", "regrip", "lower", "push", "back_off"}
    print(f"\n{F} frames @ {fps:g} fps = {F / fps:.1f} s")
    print(f"{'phase':13s} {'frames':>9s} {'ik cm':>6s} {'table':>6s} {'gap~':>6s} "
          f"{'gap=':>6s} {'thumb':>6s} {'rad/s':>6s} {'rad/s2':>7s} {'arm':>5s} "
          f"{'hand':>5s}  closest (L|R)")
    report = []
    for name, a, b in phases:
        sl = slice(a, b + 1)
        row = dict(
            phase=name, start=a, end=b, ik_err_cm=float(e[sl].max()),
            table_exact_cm=float(np.nanmin(table[sl])),
            arm_gap_cm=float(np.nanmin(gap[sl])),
            arm_gap_exact_cm=float(np.nanmin(gap_x[sl])),
            thumb_finger_gap_cm=float(np.nanmin(tf_gap[sl])),
            max_rad_s=float(vel[max(a - 1, 0):b].max()) if b > 0 else 0.0,
            max_rad_s2=float(acc[max(a - 2, 0):max(b - 1, 1)].max()),
            arm_limit_deg=float(np.degrees(lim[sl][:, arm_cols].min())),
            hand_limit_deg=float(np.degrees(lim[sl][:, hand_cols].min())),
            closest=who[a + int(np.nanargmin(gap[sl]))],
            bound_switches=[
                f"{names[j]}@{a + int(i) + 1}"
                for j in np.flatnonzero(moving)
                for i in np.flatnonzero(np.diff(on[max(a - 1, 0):b + 1, j].astype(int)))
            ] if name in tracked else [])
        report.append(row)
        print(f"{name:13s} {a:4d}-{b:4d} {row['ik_err_cm']:6.3f} "
              f"{row['table_exact_cm']:6.2f} {row['arm_gap_cm']:6.2f} "
              f"{row['arm_gap_exact_cm']:6.2f} {row['thumb_finger_gap_cm']:6.2f} "
              f"{row['max_rad_s']:6.2f} {row['max_rad_s2']:7.1f} "
              f"{row['arm_limit_deg']:5.1f} {row['hand_limit_deg']:5.1f}  {row['closest']}"
              + ("   BOUND: " + " ".join(row["bound_switches"])
                 if row["bound_switches"] else ""))
    print("columns: ik = worst hard contact error; table = lowest mesh vertex "
          "(exact); gap~ / gap= = left-right clearance by covering spheres / "
          "vertex-sampled mesh (reads <= 0.1 cm high); thumb = thumb-to-fingers "
          "(spheres); arm / hand = smallest joint-limit margin (deg) over the "
          "joints the motion uses; BOUND = joints reaching / leaving a bound "
          "while tracked (each one is a small kink)")
    ph = {n: (a, b) for n, a, b in phases}
    rake_low = float(np.nanmin(table[ph.get("lower", ph["push"])[0]:ph["back_off"][1] + 1]))

    # world link transforms from the bench itself (what renders / exports use)
    body_q = np.zeros((F, bench.model.body_count, 7), dtype=np.float32)
    for f in range(F):
        bench.joint_q[:] = joint_q[f]
        body_q[f] = np.asarray(bench._fk())
    out = dict(
        joint_q=joint_q, fps=float(fps),
        phase_names=np.array([p[0] for p in phases]),
        phase_start=np.array([p[1] for p in phases]),
        phase_end=np.array([p[2] for p in phases]),
        joint_names=np.array([f"left_{n}" for n in kl.joint_names]
                             + [f"right_{n}" for n in kr.joint_names]),
        body_q=body_q, body_names=np.array(bench.body_labels),
        target_left=targets["left"], target_right=targets["right"],
        table_exact_cm=table, arm_gap_cm=gap, arm_gap_exact_cm=gap_x,
        thumb_finger_gap_cm=tf_gap,
        scene=json.dumps(dict(
            scale=S, yc=yc, floor_z=0.0, zlift=args.zlift,
            card_cm=[CARD_LEN * S, CARD_DEPTH * S], cards_per_packet=27,
            packet_thickness_cm=thick, packet_tilt_deg=float(args.tilt), top_x=float(top_x),
            stack_dir=n_p.tolist(), card0_centre_left=centre.tolist(),
            T0=T0.tolist(), G0=G0.tolist(),
            T_bow=T0_bow.tolist(), G_bow=G0_bow.tolist(),
            thumb_contact=Tc.tolist(), finger_contact=Gc.tolist(), thumb_inset_cm=float(args.thumb_inset),
            bow_thumb=float(args.bow_thumb), bow_fingers=float(args.bow_fingers), pad_tilt_deg=float(args.pad_tilt),
            bow_dir=args.bow_dir, thumb_grasp=args.thumb_grasp, riffle_lift_cm=float(args.riffle_lift), thumb_open_deg=float(args.thumb_open), riffle_lift_early=[float(v) for v in args.riffle_lift_early], riffle_roll_deg=float(args.riffle_roll), riffle_roll_from=float(args.riffle_roll_from), riffle_knuckle_deg=float(args.riffle_knuckle), riffle_knuckle_from=float(args.riffle_knuckle_from), riffle_knuckle_frames=float(args.riffle_knuckle_frames), riffle_knuckle_mode=args.riffle_knuckle_mode, riffle_hold_depth_from=float(args.riffle_hold_depth_from), riffle_knuckle_press=[float(v) for v in args.riffle_knuckle_press], riffle_knuckle_press_from=float(args.riffle_knuckle_press_from), riffle_cut=float(args.riffle_cut), push_z_cm=float(args.push_z), riffle_extra_cm=float(args.riffle_extra), riffle_hold_axis=bool(args.riffle_hold_axis), riffle_stair_cm=float(args.riffle_stair), riffle_stair_gap_cm=float(args.riffle_stair_gap), riffle_stair_jump_frames=float(args.riffle_stair_jump), riffle_hand=bool(args.riffle_hand), riffle_mode=args.riffle_mode, bow_fingers_dir=args.bow_fingers_dir, index_press_cm=float(args.index_press), index_gap_cm=float(args.index_gap), index_from=args.index_from,
            finger_dy=FINGER_DY, rake_x=[x_out, x_in], rake_z=z_rake,
            lift_clear_cm=float(args.lift_clear),
            rake_speed_cm_s=abs(v_push), rake_lowest_cm=rake_low,
            release_lag_frames=lag,
            note="left-hand values (mirror x for the right hand); T0/G0 = "
                 "card 0's upper-inner / lower-outer edge, *_bow after the "
                 "bow; thumb_contact = middle of the upper end face, "
                 "finger_contact = the point of the lower end face at the "
                 "fingertips' working height (its middle at 45 deg); fingers sit "
                 "at finger_contact + (0, finger_dy, 0). The fingertip pads are "
                 "near-vertical (distal phalanges 7-35 deg off), not normal "
                 "to the tilted end face: the top cards' lower edge sits "
                 "~0.3 cm inside the pads, card 0's ~0.4 cm clear. rake_lowest_cm "
                 "= lowest hand vertex while raking (rounded tips: the flat "
                 "pad face spans z ~0.6-1.5 cm and recedes below)")))
    return out, report


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--out", default="output/ik/shuffle_motion")
    ap.add_argument("--fps", type=float, default=50.0,
                    help="50 = the contact solver's h = 0.02 s")
    ap.add_argument("--scale", type=float, default=1.25)
    ap.add_argument("--yc", type=float, default=30.0, help="scene depth (cm)")
    ap.add_argument("--zlift", type=float, default=0.6,
                    help="packets above the table (cm)")
    ap.add_argument("--riffle-step", type=float, default=0.04,
                    help="riffle: seconds per card per hand (reference 0.04)")
    ap.add_argument("--release-lag", type=float, default=-1.0,
                    help="left hand trails the right by this many seconds in "
                         "the riffle; < 0: the reference's one solver step")
    ap.add_argument("--tilt", type=float, default=45.0,
                    help="packet tilt from the table (deg); reference 45")
    ap.add_argument("--top-x", type=float, default=-1.0,
                    help="|x| of card 0's upper-inner edge (cm); <= 0: the "
                         "reference's 2.32")
    ap.add_argument("--direct-push", action="store_true",
                    help="no lift-off between the riffle and the push: park the thumb "
                         "with the fingertips in place (phase 'regrip'), then push")
    ap.add_argument("--regrip-time", type=float, default=0.8, help="seconds")
    ap.add_argument("--push-z", type=float, default=0.0, help="cm the fingertips rise over the push (0 = the push stays at the rake height)")
    ap.add_argument("--push-pause", type=float, default=0.0, help="seconds the hands hold still between the thumb's withdrawal and the push (--direct-push)")
    ap.add_argument("--regrip-retreat", type=float, default=0.0,
                    help="fingertips move out by this much (cm) during the regrip")
    ap.add_argument("--lift-clear", type=float, default=0.0,
                    help="after the riffle, lift the grasp straight up by this much (cm) "
                         "before the joint-space lift-off; 0: none (the original motion)")
    ap.add_argument("--lift-clear-time", type=float, default=0.5,
                    help="duration of the straight lift (s)")
    ap.add_argument("--rake-start", type=float, default=-1.0,
                    help="|x| where the rake comes down (cm); <= 0: where the "
                         "reference plates start (9 cm x scale)")
    ap.add_argument("--table-gap", type=float, default=0.2,
                    help="fingertips stay this far above the table (cm)")
    ap.add_argument("--bow", type=float, default=BOW, help="cm at scale 1")
    ap.add_argument("--index-press", type=float, default=0.0, help="cm down the card from the top edge at which the index fingertip presses "
                    "the packet's outer face through the hold, bow and riffle (0 = the index joins the other fingers at the feet)")
    ap.add_argument("--index-from", choices=("approach", "bow"), default="approach", help="when the index takes its press target: from "
                    "the approach (held through hold and bow) or arriving over the second half of the bow")
    ap.add_argument("--index-gap", type=float, default=0.2, help="cm the index tip point is held outside the packet's outer face")
    ap.add_argument("--index-weight", type=float, default=1.0, help="weight of the index press position term")
    ap.add_argument("--bow-fingers-dir", choices=("auto", "card", "inward"), default="auto", help="direction of the fingers' bow motion: "
                    "auto follows --bow-dir; inward (the reference's) with --bow-dir card lets the thumb press along the card while the "
                    "fingers push the feet up the fingertip caps, which stacks the feet parallel to the held ends and evens out the "
                    "cards' compression (contact-solver feedback: feet stacked flat on the mat leave the inner cards bowed 10 mm and "
                    "the outer ones 1.5 mm)")
    ap.add_argument("--pad-tilt", type=float, default=0.0, help="degrees the fingertip pads face up from the horizontal in the grasp "
                    "(0 = vertical pads, the reference; --tilt = facing the packet's lower end face)")
    ap.add_argument("--packet-thick", type=float, default=-1.0, help="thickness of a 27-card packet (cm at scale 1; default the reference "
                    "%.3f = a 0.39 mm pitch at scale 1.25; 0.65 stacks 0.3 mm cards at their own thickness)" % PACKET_THICK)
    ap.add_argument("--riffle-stair", type=float, default=0.0, help="cm of card pitch across the stack: the riffle sweep becomes a "
                    "staircase, one jump of this size per card period (0 = constant-speed sweep)")
    ap.add_argument("--riffle-stair-gap", type=float, default=0.25, help="cm the pad's edge is from the first card at the riffle's start "
                    "(covered by a smooth approach over the first 1/28 of the riffle)")
    ap.add_argument("--riffle-stair-jump", type=float, default=2.0, help="frames each staircase jump takes")
    ap.add_argument("--riffle-mode", choices=("sweep", "lift"), default="sweep", help="sweep: the thumb slides across the stack "
                    "(the reference); lift: it only retreats up the card axis by --riffle-lift, --riffle-stair-gap of it quickly, the rest "
                    "evenly over 27 periods (with --riffle-stair-jump frames of motion per period; a period's length makes it continuous)")
    ap.add_argument("--riffle-hand", action="store_true", help="the riffle sweep moves the whole hand (arm and finger flexion, "
                    "fingertips held, thumb joints frozen) instead of the thumb alone, so the thumb keeps its orientation")
    ap.add_argument("--riffle-hand-weight", type=float, default=5.0, help="--riffle-hand: weight of the wrist position and orientation terms")
    ap.add_argument("--riffle-hand-posture", type=float, default=0.5, help="--riffle-hand: weight of the frame-to-frame posture anchor")
    ap.add_argument("--riffle-axis-weight", type=float, default=0.5, help="weight of the riffle's tip-direction term (--riffle-hold-axis, "
                    "--riffle-roll); the tip's position term has weight 1")
    ap.add_argument("--riffle-hold-axis", action="store_true", help="keep the thumb tip's direction of the grasp through the riffle "
                    "(a soft term; without it only the tip's position is prescribed and the tip may turn as it slides)")
    ap.add_argument("--riffle-extra", type=float, default=0.0, help="cm added to the riffle's sweep across the stack (the reference sweeps "
                    "the packet's thickness plus --thumb-inset; a pad on the thumb whose inner edge trails the tip needs more)")
    ap.add_argument("--riffle-roll-from", type=float, default=0.0, help="frame of the riffle at which --riffle-roll starts (0 = its first frame)")
    ap.add_argument("--riffle-knuckle", type=float, default=0.0, help="degrees the thumb's last knuckle (thumb_IP) opens from frame "
                    "--riffle-knuckle-from of the riffle on, the rest of the thumb holding that frame's pose (0 = the reference: "
                    "the thumb slides across the edges to the riffle's end)")
    ap.add_argument("--riffle-knuckle-from", type=float, default=25.0, help="frame of the riffle (from its first frame) at which "
                    "--riffle-knuckle starts; 25 = 0.5 s in")
    ap.add_argument("--riffle-knuckle-frames", type=float, default=0.0, help="frames over which --riffle-knuckle opens (0 = the rest of the riffle)")
    ap.add_argument("--riffle-hold-depth-from", type=float, default=0.0, help="frame of the riffle from which the --riffle-lift "
                    "withdrawal or descent stops, the tip keeping its depth along the card axis (0 = off)")
    ap.add_argument("--riffle-cut", type=float, default=0.0, help="emit only the first F frames of the riffle (its schedule "
                    "unchanged) and go on to the withdrawal, park, pause and push from there (0 = the whole riffle)")
    ap.add_argument("--riffle-knuckle-press-from", type=float, default=0.0, help="frame of the riffle at which --riffle-knuckle-press "
                    "starts (0 = with the knuckle, --riffle-knuckle-from)")
    ap.add_argument("--riffle-knuckle-mode", choices=("freeze", "slide"), default="freeze", help="freeze: the thumb stops sliding "
                    "when the knuckle starts; slide: the tip keeps following the riffle's path, the other thumb joints solving it")
    ap.add_argument("--riffle-knuckle-press", type=float, nargs=2, default=[0.0, 100.0], metavar=("CM", "FRAMES"),
                    help="an extra descent of the thumb down the card axis (cm) over FRAMES from the knuckle's start frame "
                    "(mode slide: added to the slide's path; mode freeze: the frozen thumb descends while its knuckle opens)")
    ap.add_argument("--riffle-roll", type=float, default=0.0, help="degrees the thumb's tip axis turns over the riffle, its end "
                    "toward the centre (0 = the reference: the tip keeps its grasp orientation while it slides across)")
    ap.add_argument("--riffle-lift-early", type=float, nargs=2, default=[0.0, 45.0], metavar=("CM", "FRAMES"),
                    help="an extra thumb motion down the card axis (cm; negative = up) over the first FRAMES of the riffle")
    ap.add_argument("--riffle-lift", type=float, default=0.0, help="cm the thumb withdraws up the card axis over the riffle (0 = the "
                    "reference: it slides across the edges at a fixed depth)")
    ap.add_argument("--thumb-grasp", choices=("tip", "pad"), default="tip",
                    help="tip: the thumb's tip point on the target with the tip pointing down (the reference); pad: the pad's apex "
                         "on the target with the pad facing down the card onto the packet's end face")
    ap.add_argument("--pad-axis-weight", type=float, default=0.5, help="weight of the pad-orientation term of --thumb-grasp pad (the tip "
                    "grasp's tip-direction term has 0.5); raise it to make the pad lie flat on the end face at the cost of position error")
    ap.add_argument("--bow-dir", choices=("vertical", "card"), default="vertical",
                    help="vertical: thumb straight down, fingers straight in (the reference); card: both along the card axis")
    ap.add_argument("--bow-thumb", type=float, default=1.0, help="the thumb's share of the bow (x --bow): 1 = the reference")
    ap.add_argument("--bow-fingers", type=float, default=1.0, help="the fingers' share of the bow (x --bow): 1 = the reference, 0 = they stay")
    ap.add_argument("--thumb-open", type=float, default=0.0, help="degrees the thumb tip's pointing direction is turned from straight "
                    "down toward the card axis in the grasp (45 = along the cards); the tip then presses the card ends more squarely")
    ap.add_argument("--thumb-inset", type=float, default=0.0,
                    help="cm (rig scale): the thumb's grasp target moved down the packet's upper end face toward card 0; "
                         "the riffle sweep still ends past the top card")
    ap.add_argument("--hover", type=float, default=7.0, help="approach height")
    ap.add_argument("--wrist-y", type=float, default=28.0,
                    help="preferred wrist depth in the grasp (soft)")
    ap.add_argument("--wrist-x", type=float, default=10.0,
                    help="wrist keep-out |x| in the grasp (cm)")
    ap.add_argument("--rake-wrist-x", type=float, default=9.0,
                    help="wrist keep-out |x| while raking (cm)")
    ap.add_argument("--link4-x", type=float, default=7.0,
                    help="forearm (link4) keep-out |x| (cm)")
    ap.add_argument("--square-slack", type=float, default=0.2,
                    help="fingertip-to-card-end gap (cm) when the rake stops; "
                         "< 0: stop where the reference plates do")
    ap.add_argument("--starts", type=int, default=40)
    ap.add_argument("--check-every", type=int, default=1,
                    help="mesh diagnostics on every Nth frame (1 = all; the "
                         "diagnostics are most of the run time)")
    args = ap.parse_args()
    out, report = build(args)
    os.makedirs(args.out, exist_ok=True)
    path = os.path.join(args.out, "shuffle_motion.npz")
    np.savez_compressed(path, **out)
    json.dump(report, open(os.path.join(args.out, "report.json"), "w"), indent=1)
    print(f"\nwrote {path}")


if __name__ == "__main__":
    main()
